name = "remotejobs-my"
compatibility_date = "2024-12-10"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "remotejobs-db"
database_id = "0f6df2af-eb3b-41cc-9d2d-ffac652d8022"

# KV bindings for sessions
[[kv_namespaces]]
binding = "SESSION"
id = "sessions"
preview_id = "sessions"
